{% set name = "zizmor" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zizmorcore/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 27da51a31dfb553a9fe0acfa3a129f0d5e55b8593c502f2c99b332e5f3156e0e

build:
  number: 0
  script:
    - export CARGO_PROFILE_RELEASE_STRIP=symbols  # [not win]
    - export RUSTFLAGS="$CARGO_BUILD_RUSTFLAGS"  # [not win]
    - export CFLAGS="$CFLAGS -D_BSD_SOURCE"  # [linux]
    - set CARGO_PROFILE_RELEASE_STRIP=symbols  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.0,<2.0  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

test:
  commands:
    - zizmor --help
    - pip check
  requires:
    - pip

about:
  home: https://docs.zizmor.sh
  summary: Static analysis for GitHub Actions
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ocefpaf
