context:
  version: 1.16.3
  name: zizmor

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/zizmorcore/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0953b0bd6016b929a743b18e693b9cf8e0f2766e53531a64134f6d762965e933

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: not win
        then:
          - export RUSTFLAGS="$CARGO_BUILD_RUSTFLAGS"
      - if: linux
        then:
          - export CFLAGS="$CFLAGS -D_BSD_SOURCE"
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.0,<2.0
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - make
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

tests:
  - script:
      - zizmor --help
      - pip check
    requirements:
      run:
        - pip

about:
  homepage: https://docs.zizmor.sh
  summary: Static analysis for GitHub Actions
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ocefpaf
    - ManuelLerchner
    - ytausch
