context:
  version: "1.29.0"

package:
  name: zizmor
  version: ${{ version }}

source:
  url: https://github.com/zizmorcore/zizmor/archive/refs/tags/v${{ version }}.tar.gz
  sha256: de3da74599a1e080361e97c0431bdc0f656ea530420fdff953a8e3d679e1153b

build:
  number: 0
  script:
    env:
      # Use cmake to build aws-lc-sys, because conda's CFLAGS inject -O2 which
      # overrides the -O0 required by jitterentropy-base.c, causing a build failure.
      AWS_LC_SYS_CMAKE_BUILDER: "1"
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: not win
        then:
          - export RUSTFLAGS="$CARGO_BUILD_RUSTFLAGS"
      - if: linux
        then:
          - export CFLAGS="$CFLAGS -D_BSD_SOURCE"
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path crates/zizmor
          - mkdir -p $PREFIX/share/zsh/site-functions $PREFIX/share/bash-completion/completions $PREFIX/share/fish/vendor_completions.d
          - zizmor --completions=zsh > $PREFIX/share/zsh/site-functions/_zizmor
          - zizmor --completions=bash > $PREFIX/share/bash-completion/completions/zizmor
          - zizmor --completions=fish > $PREFIX/share/fish/vendor_completions.d/zizmor.fish
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path crates\zizmor
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - cmake
    - make

tests:
  - script:
      - zizmor --help
  - package_contents:
      bin:
        - zizmor
      files:
        - if: unix
          then:
            - share/bash-completion/completions/zizmor
            - share/fish/vendor_completions.d/zizmor.fish
            - share/zsh/site-functions/_zizmor
      strict: true

about:
  homepage: https://docs.zizmor.sh
  repository: https://github.com/zizmorcore/zizmor
  summary: Static analysis for GitHub Actions
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ocefpaf
    - ManuelLerchner
    - ytausch
